[package]
name = "token-faucet-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_token_faucet"

[dependencies]
solana-program = "2.1.17"
borsh = "1.5.1"
getrandom = { version = "0.1", features = ["dummy"] }