[package]
name = "token-faucet-program"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_token_faucet"

[dependencies]
solana-sdk = "2.2.1"
solana-program = "2.2.1"
borsh = "1.5.5"